spring:
  application:
    name: user-service
  profiles:
    active:
    - dev

server:
  port: 8081
  error:
    include-stacktrace: never

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
